### ISSUE TITLE
we do not have acess to the datasets of code.

### ISSUE THREAD

**Issue by Ayanzadeh93** [Shenggan/DeepCell-Keras#1]
we do not have acess to the datasets of code. the link you put is not accessible and when i run your bash code for downloading the dataset. i faced with the link has been refused message.

**Comment by Shenggan** [comment]
Sorry for the server has been shut down, and I can not find the dataset either. I think you can try to find dataset from https://github.com/CovertLab/DeepCell.

**Comment by Ayanzadeh93** [comment]
Thanks for  your response and sharing this link with me.
